export const languages = [
            { id: 1,
              name: "\"Javascript\",",
              logo: "https://seeklogo.com/images/J/javascript-js-logo-2949701702-seeklogo.com.png",
            },
            { id: 2,
              name: "\"Node.js\",",
              logo: "https://seeklogo.com/images/N/nodejs-logo-065257DE24-seeklogo.com.png",
            },
            { id: 3,
              name: "\"Ruby\",",
              logo: "https://seeklogo.com/images/R/ruby-logo-087AF79367-seeklogo.com.jpg",
            },
            { id: 4,
              name: "\"CSS\",",
              logo: "https://seeklogo.com/images/C/css3-logo-8724075274-seeklogo.com.png",
            },
            { id: 5,
              name: "\"HTML\",",
              logo: "https://seeklogo.com/images/H/html5-logo-EF92D240D7-seeklogo.com.png",
            },
          ]

export const databases = [
          { id: 1,
            name: "\"SQL\",",
            logo: "http://www.logospng.com/images/44/sql-amp-mysql-education-training-blazing-softech-pvt-ltd-44396.png",
          },
        ]

export const frameworks = [
          { id: 1,
            name: "\"React\",",
            logo: "https://seeklogo.com/images/R/react-logo-7B3CE81517-seeklogo.com.png",
          },
          { id: 2,
            name: "\"Next.js\",",
            logo: "https://cloud.githubusercontent.com/assets/50838/24116055/7076ba9c-0dcb-11e7-93d0-ba8f9ac8f6e4.png",
          },
          { id: 3,
            name: "\"Rails\",",
            logo: "https://dcresource.biz/wp-content/uploads/2016/03/ruby_on_rails.png",
          },
          { id: 4,
            name: "\"Express.js\",",
            logo: "https://seeklogo.com/images/E/express-js-logo-FA36FF1D3F-seeklogo.com.png",
            check: true
          },
          { id: 5,
            name: "\"React-Router\",",
            logo: "https://seeklogo.com/images/R/react-router-logo-AB5BFB638F-seeklogo.com.png",
            check: true
          },
          { id: 6,
            name: "\"Material UI\",",
            logo: "https://seeklogo.com/images/M/material-ui-logo-527EE4ADD9-seeklogo.com.png",
          },
          { id: 7,
            name: "\"Materialize\",",
            logo: "https://seeklogo.com/images/M/materialize-logo-0FCAD8A6F8-seeklogo.com.png",
            check: true
          },
          { id: 8,
            name: "\"Bootstrap\",",
            logo: "https://seeklogo.com/images/B/bootstrap-logo-3C30FB2A16-seeklogo.com.png",
          },
        ]

export const otherSkills = [
          { id: 1,
            name: "\"npm\",",
            logo: "https://seeklogo.com/images/N/npm-node-package-manager-logo-DE93649ED1-seeklogo.com.png",
            check: true
          },
          { id: 2,
            name: "\"Yarn\",",
            logo: "https://seeklogo.com/images/Y/yarn-logo-F5E7A65FA2-seeklogo.com.png",
          },
          { id: 3,
            name: "\"Git\",",
            logo: "https://seeklogo.com/images/G/git-logo-CD8D6F1C09-seeklogo.com.png",
          },
          { id: 4,
            name: "\"Github\",",
            logo: "https://seeklogo.com/images/G/github-logo-7880D80B8D-seeklogo.com.png",
          },
          { id: 5,
            name: "\"AWS Cognito\",",
            logo: "https://seeklogo.com/images/A/aws-cognito-logo-ADE65FC971-seeklogo.com.png",
          },
          { id: 6,
            name: "\"Photoshop\",",
            logo: "https://seeklogo.com/images/A/adobe-photoshop-cc-logo-CBD0AAA3A7-seeklogo.com.png",
          },
          { id: 7,
            name: "\"GIMP\",",
            logo: "https://seeklogo.com/images/G/gimp-logo-4D0E1F6FF5-seeklogo.com.jpg",
          },
        ]

export const testing = [
          { id: 1,
            name: "\"Jest\",",
            logo: "https://seeklogo.com/images/J/jest-logo-F9901EBBF7-seeklogo.com.png",
          },
          { id: 2,
            name: "\"RSPEC\",",
            logo: "http://rspec.info/images/logo_ogp.png",
          },
        ]
